services:
  puppeteer:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./konto/downloads:/app/konto/downloads
      - ./kk/downloads:/app/kk/downloads
    tty: true
    stdin_open: true
    restart: unless-stopped
    shm_size: '512m'