version: '3.8'

services:
  puppeteer:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./downloads:/app/downloads
    tty: true
    stdin_open: true
    restart: unless-stopped
    shm_size: '512m'